import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {createServer,verifySignature} from '../server.mjs';
const origin='https://visitquill.onrender.com',secret='test-only-webhook-secret';
async function fixture(t,overrides={}){let session;const calls=[];const server=createServer({key:'ck_live_test_fixture',webhookSecret:secret,fetcher:async(url,options)=>{calls.push({url,options});let data;if(url.endsWith('/app'))data={environment:'production',status:'live'};else if(url.endsWith('/connect/sessions')){const b=JSON.parse(options.body);session={id:'cs_'+'a'.repeat(20),externalId:b.externalId,categories:b.categories,environment:'production',status:'completed',subject:'u_'+'b'.repeat(16),sync:{grantedCategories:b.categories}};data={...session,url:'https://finchnode.com/connect/'+session.id};}else if(url.includes('/connect/sessions/'))data=session;else data={id:session.subject,object:'health_record',categories:session.categories,consent:{status:'active'},data:{},meta:{}};return {ok:true,json:async()=>data};},...overrides});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r)}));const base=`http://127.0.0.1:${server.address().port}`;const call=(path,options={})=>fetch(base+path,{...options,headers:{Origin:origin,'Content-Type':'application/json',...options.headers}});return {call,calls,getSession:()=>session};}
async function connect(call){const r=await call('/session',{method:'POST',body:JSON.stringify({categories:['labs']})});assert.equal(r.status,201);return r.json();}
test('missing credentials fail closed; sandbox key cannot connect',async t=>{const {call}=await fixture(t,{key:'ck_test_example'});assert.equal((await call('/session',{method:'POST',body:'{"categories":["labs"]}'})).status,503)});
test('anonymous clients cannot list users or select a patient; origins and scopes are restricted',async t=>{const {call}=await fixture(t);assert.equal((await call('/records')).status,401);assert.equal((await call('/session',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'})).status,403);assert.equal((await call('/session',{method:'POST',body:'{"categories":["claims"]}'})).status,400);assert.equal((await call('/session',{method:'POST',body:'{"categories":["labs"],"subject":"other"}'})).status,400)});
test('session is bound to origin, has no arbitrary proxy, and reads only granted categories',async t=>{const {call,calls}=await fixture(t);const {token}=await connect(call);const headers={Authorization:'Bearer '+token};assert.equal((await call('/records',{headers:{...headers,Origin:'https://dosefolio.onrender.com'}})).status,401);const r=await call('/records',{headers});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal((await r.json()).environment,'production');assert.ok(calls.at(-1).url.endsWith('/records?categories=labs'));assert.equal((await call('/users',{headers})).status,404);await call('/session',{method:'DELETE',headers});assert.equal((await call('/records',{headers})).status,401)});
test('live configuration and session environment are validated',async t=>{const {call}=await fixture(t,{fetcher:async()=>({ok:true,json:async()=>({environment:'sandbox',status:'sandbox'})})});assert.equal((await call('/session',{method:'POST',body:'{"categories":["labs"]}'})).status,503)});
test('signed revocation invalidates access; forged and stale signatures are rejected',async t=>{const {call,getSession}=await fixture(t);const {token}=await connect(call);await call('/records',{headers:{Authorization:'Bearer '+token}});const raw=JSON.stringify({type:'consent.revoked',data:{subject:getSession().subject}}),stamp=Math.floor(Date.now()/1000);const signature='t='+stamp+',v1='+createHmac('sha256',secret).update(`${stamp}.${raw}`).digest('hex');assert.equal((await call('/webhooks/finchnode',{method:'POST',body:raw,headers:{'FinchNode-Signature':'t=0,v1=bad'}})).status,401);assert.equal((await call('/webhooks/finchnode',{method:'POST',body:raw,headers:{'FinchNode-Signature':signature,'FinchNode-Event-Id':'evt-test'}})).status,200);assert.equal((await call('/records',{headers:{Authorization:'Bearer '+token}})).status,401);assert.equal(verifySignature(raw,signature,secret,Date.now()+600000),false)});
test('session expires even if its token remains in the browser',async t=>{let time=Date.now();const {call}=await fixture(t,{now:()=>time});const {token}=await connect(call);time+=31*60000;assert.equal((await call('/records',{headers:{Authorization:'Bearer '+token}})).status,401)});
test('inactive consent and malformed data are never returned',async t=>{const {call,getSession}=await fixture(t);const {token}=await connect(call);getSession().externalId='wrong';assert.equal((await call('/records',{headers:{Authorization:'Bearer '+token}})).status,403)});
